# --- DATOS DE SONARCLOUD---
sonar.organization=patxi-bueno
sonar.projectKey=PatxiBueno_oauth2-springboot-angular-googlesignin-poc

# --- CONFIGURACIÓN GLOBAL ---
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Definimos los 3 módulos 
sonar.modules=auth,resource,front

# --- MÓDULO 1: Authorization Server (Java) ---
auth.sonar.projectName=Authorization Server
auth.sonar.projectBaseDir=authorization-server
auth.sonar.sources=src/main/java
auth.sonar.java.binaries=target/classes

# --- MÓDULO 2: Resource Server (Java) ---
resource.sonar.projectName=Resource Server
resource.sonar.projectBaseDir=resource-server
resource.sonar.sources=src/main/java
resource.sonar.java.binaries=target/classes

# --- MÓDULO 3: Frontend (Angular) ---
front.sonar.projectName=Frontend App
front.sonar.projectBaseDir=ag-prueba-front
front.sonar.sources=src
front.sonar.exclusions=**/node_modules/**,**/*.spec.ts
front.sonar.tests=src
front.sonar.test.inclusions=**/*.spec.ts